{
    "events" : [
        {
            "id":1,
            "isActive":1,
            "title":"",
            "description":"",
            "avg_point":8.7
        },
        {
            "id":2,
            "isActive":1,
            "title":"",
            "description":"",
            "avg_point":8
        },
        {
            "id":3,
            "isActive":1,
            "title":"",
            "description":"",
            "avg_point":6
        },
        {
            "id":4,
            "isActive":1,
            "title":"",
            "description":"",
            "avg_point":7.5
        },
        {
            "id":5,
            "isActive":1,
            "title":"",
            "description":"",
            "avg_point":7.1
        },
        {
            "id":6,
            "isActive":1,
            "title":"",
            "description":"",
            "avg_point":8.2
        },
        {
            "id":7,
            "isActive":1,
            "title":"",
            "description":"",
            "avg_point":7.8
        }
    ]
}